name = "FastTranspose"
uuid = "c672cb4e-dd10-4a00-b22f-8edf27ea5534"
authors = ["Harmen Stoppels <harmenstoppels@gmail.com>"]
version = "0.1.0"

[deps]
SIMDPirates = "21efa798-c60a-11e8-04d3-e1a92915a26a"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Random", "Test"]
